sites_raw <- readxl::read_xlsx(
  fs::path(pcctc::define_root(), "Sites", "SiteID.xlsx"),
  sheet = "Site ID"
)

sites <- sites_raw %>%
  janitor::clean_names() %>%
  filter(!site_id %in% c("ALL", "Movember", "PCCTC")) %>%
  dplyr::mutate(
    site_id = as.numeric(site_id),
    site_code = stringr::str_pad(site_id, width = 2, pad = "0")
  ) %>%
  dplyr::select(
    site_id, site_code, site_name,
    site_name_short = short_name,
    site_name_true_nth = true_nth_site_name_c16_170_ironman,
    site_country = country
  ) %>%
  arrange(site_id)

datapasta::dpasta(sites)

library(tidyverse)


site_to_country <- tibble::tribble(
  ~site_id, ~site_code,                                                            ~site_name,          ~site_name_short,                                                   ~site_name_true_nth,  ~site_country,
  1,       "01",                                        "Dana-Farber Cancer Institute",                    "DFCI",                                        "Dana-Farber Cancer Institute",          "USA",
  2,       "02",                                    "Duke Comprehensive Cancer Center",                    "Duke",                                    "Duke Comprehensive Cancer Center",          "USA",
  3,       "03",                           "Sidney Kimmel Comprehensive Cancer Center",                     "JHU",                           "Sidney Kimmel Comprehensive Cancer Center",          "USA",
  4,       "04",                                           "MD Anderson Cancer Center",                   "MDACC",                                                                    NA,          "USA",
  5,       "05",                                              "University of Michigan",                   "UMich",                                              "University of Michigan",          "USA",
  6,       "06",                              "Memorial Sloan-Kettering Cancer Center",                     "MSK",                              "Memorial Sloan Kettering Cancer Center",          "USA",
  7,       "07",                            "Oregon Health and Sciences Cancer Center",                    "OHSU",                            "Oregon Health and Sciences Cancer Center",          "USA",
  8,       "08",                           "University of California at San Francisco",                    "UCSF",                                                                    NA,          "USA",
  9,       "09",                             "University of Washington Medical Center",                   "UWash",                                            "University of Washington",          "USA",
  10,       "10",                                             "University of Wisconsin",                   "UWisc",                                             "University of Wisconsin",          "USA",
  11,       "11",                                               "University of Chicago",                "UChicago",                                               "University of Chicago",          "USA",
  12,       "12",                              "Rutgers Cancer Institute of New Jersey",                    "CINJ",                                                                    NA,          "USA",
  13,       "13",                      "Wayne St. University Karmanos Cancer Institute",                     "KCC",                      "Wayne St. University Karmanos Cancer Institute",          "USA",
  14,       "14",                                "Beth Israel Deaconess Medical Center",                   "BIDMC",                                                                    NA,          "USA",
  15,       "15",                                "University of Colorado Cancer Center",               "UColorado",                                                                    NA,          "USA",
  16,       "16",                                  "NorthShore University HealthSystem",              "NorthShore",                                                                    NA,          "USA",
  17,       "17", "Robert H. Lurie Comprehensive Cancer Center Northwestern University",            "Northwestern", "Robert H. Lurie Comprehensive Cancer Center Northwestern University",          "USA",
  18,       "18",                                            "University of New Mexico",                     "UNM",                                                                    NA,          "USA",
  19,       "19",                                  "Sunny Brooke Health Science Centre",                   "SBHSC",                                                                    NA,       "Canada",
  20,       "20",                "University Hospital Southampton NHS Foundation Trust",         "Southampton NHS",                "University Hospital Southampton NHS Foundation Trust",      "England",
  21,       "21",                                           "Universitätsspital Zürich",                  "Zürich",                                           "Universitätsspital Zürich",  "Switzerland",
  22,       "22",                                           "Decatur Memorial Hospital",                 "Decatur",                                                                    NA,          "USA",
  23,       "23",                                                     "Rush University",                    "Rush",                                                                    NA,          "USA",
  24,       "24",                                                  "University of Utah",                   "UUtah",                                                                    NA,          "USA",
  25,       "25",                                                  "Indiana University",                "IndianaU",                                                                    NA,          "USA",
  26,       "26",                                  "University of California San Diego",                    "UCSD",                                  "University of California San Diego",          "USA",
  27,       "27",                                              "Miami Cancer Institute",                     "MCI",                                                                    NA,          "USA",
  28,       "28",                                                    "Cleveland Clinic",        "Cleveland Clinic",                                                                    NA,          "USA",
  29,       "29",                                                         "Aria Health",             "Aria Health",                                                                    NA,          "USA",
  30,       "30",                                                   "Doylestown Health",              "Doylestown",                                                   "Doylestown Health",          "USA",
  31,       "31",                                                     "Easton Hospital",                  "Easton",                                                                    NA,          "USA",
  32,       "32",                                               "Reading Health System",                 "Reading",                                               "Reading Health System",          "USA",
  33,       "33",                                          "Baylor College of Medicine",                  "Baylor",                                          "Baylor College of Medicine",          "USA",
  34,       "34",                                       "Australian Urology Associates",                     "AUA",                                 "Australian Urology Associates (AUA)",    "Australia",
  35,       "35",                                   "University of Illinois at Chicago",               "UIllinois",                                   "University of Illinois at Chicago",          "USA",
  36,       "36",                                                 "Columbia University",                "Columbia",                                                 "Columbia University",          "USA",
  37,       "37",                                                      "Eastern Health",          "Eastern Health",                                                      "Eastern Health",    "Australia",
  38,       "38",                                                    "BC Cancer Agency",                    "BCCA",                                                    "BC Cancer Agency",       "Canada",
  39,       "39",                                            "Kantonsspital St. Gallen",                     "KSG",                                           "Kantonsspitals St. Gallen",  "Switzerland",
  40,       "40",                                       "Macquarie University Hospital",                     "MUH",                                       "Macquarie University Hospital",    "Australia",
  41,       "41",                                                   "Westmead Hospital",                      "WH",                                                   "Westmead Hospital",    "Australia",
  42,       "42",                     "Christiana Care (Helen F. Graham Cancer Center)",              "Christiana",                                                                    NA,          "USA",
  43,       "43",                                         "Princess Alexandra Hospital",                     "PAH",                                         "Princess Alexandra Hospital",    "Australia",
  44,       "44",                              "The Royal Marsden NHS Foundation Trust",       "Royal Marsden NHS",                              "The Royal Marsden NHS Foundation Trust",      "England",
  45,       "45",                                                    "Redland Hospital",        "Redland Hospital",                                                    "Redland Hospital",    "Australia",
  46,       "46",                                                     "Beacon Hospital",                  "Beacon",                                                     "Beacon Hospital",      "Ireland",
  47,       "47",                                      "Kantonsspital Grabünden (Chur)",                     "KGC",                                                 "Kantonsspitals Chur",  "Switzerland",
  48,       "48",                    "Cross Cancer Institute (Alberta Health Services)",                     "CCI",                    "Cross Cancer Institute (Alberta Health Services)",       "Canada",
  49,       "49",                                     "Princess Margaret Cancer Center",                     "PMH",                                     "Princess Margaret Cancer Center",       "Canada",
  50,       "50",                          "Vall d'Hebron Institute of Oncology (VHIO)",                    "VHIO",                                 "Vall d'Hebron Institute of Oncology",        "Spain",
  51,       "51",                                             "Tom Baker Cancer Centre",                    "TBCC",                                                                    NA,       "Canada",
  52,       "52",                                            "Juravinski Cancer Centre",                     "JCC",                                            "Juravinski Cancer Centre",       "Canada",
  53,       "53",                                       "Ottawa Hospital Cancer Centre",                    "OHCC",                                       "Ottawa Hospital Cancer Centre",       "Canada",
  54,       "54",                           "Winship Cancer Institute Emory University",                   "WCIEU",                           "Winship Cancer Institute Emory University",          "USA",
  55,       "55",                                           "Skane University Hospital",                     "SUH",                                           "Skane University Hospital",       "Sweden",
  56,       "56",                           "Guy’s and St Thomas’ NHS Foundation Trust",                  "GSTNHS",                                "Guys St. Thomas NHS Foundation Trust",      "England",
  57,       "57",                               "Comprehensive Cancer Center of Nevada",                    "CCCN",                                                                    NA,          "USA",
  58,       "58",                          "Brown University/Lifespan Cancer Institute",                   "Brown",                                                                    NA,          "USA",
  59,       "59",                                                  "Tygerberg Hospital",                      "TH",                                                                    NA, "South Africa",
  60,       "60",                                                   "MidLantic Urology",               "MidLantic",                                                                    NA,          "USA",
  61,       "61",                                 "MD Anderson Cancer Center at Cooper",                  "Cooper",                                                                    NA,          "USA",
  62,       "62",                              "Chesapeake Urology Research Associates",                    "CURA",                                       "Chesapeake Urology Associates",          "USA",
  63,       "63",                                     "Centro de Pesquisa em Oncologia",                     "CPO",                                     "Centro de Pesquisa em Oncologia",       "Brazil",
  64,       "64",                                                 "Millennium Oncology",              "Millennium",                                                                    NA,          "USA",
  65,       "65",                                      "CHU de Québec-Université Laval",                     "CHU",                                    "CHU de Quebec - Universite Laval",       "Canada",
  66,       "66",                      "Centre Hospitalier de l'Université de Montréal",                    "CHUM",                      "Centre Hospitalier de l'Université de Montréal",       "Canada",
  67,       "67",                                                  "Epworth Healthcare",                 "Epworth",                                                  "Epworth Healthcare",    "Australia",
  68,       "68",                                            "Allegheny Health Network",               "Allegheny",                                                                    NA,          "USA",
  69,       "69",                                          "Örebro University Hospital",                  "Örebro",                                          "Örebro University Hospital",       "Sweden",
  70,       "70",                                             "University of Rochester",              "URochester",                                                                    NA,          "USA",
  71,       "71",                              "Erasmus University MC Cancer Institute",                 "Erasmus",                                                                    NA,  "Netherlands",
  72,       "72",                                   "The Christie NHS Foundation Trust",            "Christie NHS",                                   "The Christie NHS Foundation Trust",      "England",
  73,       "73",                     "Stephenson Cancer Center University of Oklahoma",               "UOklahoma",                                                                    NA,          "USA",
  74,       "74",                 "University of Massachusetts Memorial Medical Center",                   "UMass",                                                                    NA,          "USA",
  75,       "75",                              "Stichting Ziekenhuisgroep Twente (ZGT)",                     "ZGT",                                                                    NA,  "Netherlands",
  76,       "76",                                "Mayo Clinic – Florida (Jacksonville)",                 "Mayo FL",                                                                    NA,          "USA",
  77,       "77",                                 "Mayo Clinic – Minnesota (Rochester)",                 "Mayo MN",                                                                    NA,          "USA",
  78,       "78",                                     "Centro de Paulista de Oncologia",                "Paulista",                                     "Centro de Paulista de Oncologia",       "Brazil",
  79,       "79",                                                        "City of Hope",                     "COH",                                                                    NA,          "USA",
  80,       "80",                                                     "Yale University",                    "Yale",                                                                    NA,          "USA",
  81,       "81",                         "Washington University Siteman Cancer Center",                   "WashU",                                                                    NA,          "USA",
  82,       "82",                                              "University of Virginia",                     "UVA",                                         "University of Virgina (UVA)",          "USA",
  83,       "83",                                   "Carolina Urologic Research Center",                    "CURC",                                                                    NA,          "USA",
  84,       "84",                                    "University of Alabama-Birmingham",                     "UAB",                                    "University of Alabama-Birmingham",          "USA",
  85,       "85",                          "Mayo Clinic – Arizona (Scottsdale/Phoenix)",                 "Mayo AZ",                                                                    NA,          "USA",
  86,       "86",                                                   "Tulane University",                  "Tulane",                                                   "Tulane University",          "USA",
  87,       "87",                                             "University of Minnesota",                   "UMinn",                                                                    NA,          "USA",
  88,       "88",                                               "Moffitt Cancer Center",                 "Moffitt",                                               "Moffitt Cancer Center",          "USA",
  89,       "89",                                "University of California Los Angeles",                    "UCLA",                                "University of California Los Angeles",          "USA",
  90,       "90",                                              "Ochsner Medical Center",                 "Ochsner",                                                                    NA,          "USA",
  91,       "91",                                             "Virginia Oncology Group",                     "VOA",                                                                    NA,          "USA",
  92,       "92",                                                   "GU Cancer Network",                    "GURN",                                                                    NA,          "USA",
  93,       "93",                                                 "New York University",                     "NYU",                                                                    NA,          "USA",
  94,       "94",                                       "Roswell Park Cancer Institute",            "Roswell Park",                                       "Roswell Park Cancer Institute",          "USA",
  95,       "95",                                        "University of North Carolina",                     "UNC",                                        "University of North Carolina",          "USA",
  96,       "96",                                        "Weill Cornell Medical Center",                    "WCMC",                                        "Weill Cornell Medical Center",          "USA",
  97,       "97",                    "The Institute of Cancer Research (Royal Marsden)",                      "RM",                                                                    NA,      "England",
  98,       "98",                                                   "Howard University",                  "Howard",                                                                    NA,          "USA",
  99,       "99",                                   "Thomas Jefferson University, CRMO",                     "TJU",                                         "Thomas Jefferson University",          "USA",
  100,      "100",                                    "Hospital Beneficência Portuguesa", "Beneficência Portuguesa",                                                                    NA,       "Brazil",
  101,      "101",                                   "Instituto do Câncer e Transplante",                     "ICT",                                   "Instituto do Câncer e Transplante",       "Brazil",
  102,      "102",                                          "Australian Prostate Centre",                     "APC",                                          "Australian Prostate Centre",    "Australia",
  103,      "103",                        "Hospital Universitario Virgen de la Victoria",   "Virgen de la Victoria",                        "Hospital Universitario Virgen de la Victoria",        "Spain",
  104,      "104",                             "Instituto Câncer do Estado de São Paulo",               "São Paulo",                             "Instituto Câncer do Estado de São Paulo",       "Brazil",
  105,      "105",                                   "St. Vincent’s University Hospital",             "St. Vincent",                                   "St. Vincent's University Hospital",      "Ireland",
  106,      "106",                                        "Hospital Clínic de Barcelona",               "Barcelona",                                        "Hospital Clínic de Barcelona",        "Spain",
  107,      "107",                                       "St. Vincent’s Hospital Sydney",         "St. Vincent SYD",                                       "St. Vincent's Hospital Sydney",    "Australia",
  108,      "108",                                           "Warrenville Cancer Center",             "Warrenville",                                           "Warrenville Cancer Center",          "USA",
  109,      "109",                                                "Delnor Cancer Center",                  "Delnor",                                                "Delnor Cancer Center",          "USA",
  110,      "110",                                            "Kishwaukee Cancer Center",              "Kishwaukee",                                            "Kishwaukee Cancer Center",          "USA",
  111,      "111",                                       "Canisius Wilhemina Ziekenhuis",                     "CWZ",                                                                    NA,  "Netherlands",
  112,      "112",                                     "Franciscus Gasthuis & Viletland",                     "SFG",                                                                    NA,  "Netherlands",
  113,      "113",                                        "Tergooi Ziekenhuis Hilversum",                 "Tergooi",                                                                    NA,  "Netherlands",
  114,      "114",                                        "Tallaght University Hospital",                "Tallaght",                                        "Tallaght University Hospital",      "Ireland",
  115,      "115",                                         "Hospital Clinico San Carlos",              "San Carlos",                                         "Hospital Clinico San Carlos",        "Spain",
  116,      "116",                                              "University of Maryland",                "Maryland",                                                                    NA,          "USA",
  117,      "117",                                "Hospital Universitario 12 de Octubre",                 "Octubre",                                "Hospital Universitario 12 de Octubre",        "Spain",
  118,      "118",                                   "Royal Brisbane & Women's Hospital",                "Brisbane",                                   "Royal Brisbane & Women's Hospital",    "Australia",
  119,      "119",                                              "Velindre Cancer Centre",                "Velindre",                                              "Velindre Cancer Centre",      "England",
  120,      "120",                     "University Hospitals of Morecambe Bay NHS Trust",               "Morecambe",                     "University Hospitals of Morecambe Bay NHS Trust",      "England",
  121,      "121",                                    "South Tyneside District Hospital",                "Tyneside",                                    "South Tyneside District Hospital",      "England",
  122,      "122",                                           "Sunderland Royal Hospital",              "Sunderland",                                                                    NA,      "England",
  123,      "123",                                    "Hospital Provincial de Castellón", "Provincial de Castellón",                                    "Hospital Provincial de Castellón",        "Spain",
  124,      "124",                  "Lancashire Teaching Hospitals NHS Foundation Trust",              "Lancashire",                  "Lancashire Teaching Hospitals NHS Foundation Trust",      "England",
  125,      "125",                                                    "Stichting Amphia",        "Stichting Amphia",                                                                    NA,  "Netherlands",
  126,      "126",                                   "Noordwest Ziekenhuisgroep Alkmaar",                     "NWZ",                                                                    NA,  "Netherlands",
  127,      "127",                          "Hospital Universitario Central de Asturias",     "Central de Asturias",                          "Hospital Universitario Central de Asturias",        "Spain",
  128,      "128",                                  "Hospital Universitario La Princesa",             "La Princesa",                                  "Hospital Universitario La Princesa",        "Spain",
  129,      "129",                                                 "Maasstad Ziekenhuis",                "Maasstad",                                                                    NA,  "Netherlands",
  130,      "130",                                "Stichting Haaglanden Medisch Centrum",              "Haaglanden",                                                                    NA,  "Netherlands",
  131,      "131",                   "Sheffield Teaching Hospitals NHS Foundation Trust",               "Sheffield",                   "Sheffield Teaching Hospitals NHS Foundation Trust",      "England",
  132,      "132",                              "Institut Catalá d’Oncologia Hospitalet",              "Hospitalet",                                                                    NA,        "Spain",
  133,      "133",                                "Institut Catalá d’Oncologia Badalona",                "Badalona",                                "Institut Catalá d'Oncologia Badalona",        "Spain",
  134,      "134",                                                    "Hospital del Mar",                 "del Mar",                                                    "Hospital del Mar",        "Spain",
  135,      "135",                                "Medical University of South Carolina",                    "MUSC",                                                                    NA,          "USA",
  136,      "136",                                          "Mount Vernon Cancer Centre",            "Mount Vernon",                                          "Mount Vernon Cancer Centre",      "England",
  137,      "137",                                                     "Lister Hospital",                  "Lister",                                                     "Lister Hospital",      "England",
  138,      "138",                    "Clatterbridge Cancer Centre NHS Foundation Trust",           "Clatterbridge",                    "Clatterbridge Cancer Centre NHS Foundation Trust",      "England",
  139,      "139",                                                        "Isala Zwolle",                   "Isala",                                                                    NA,  "Netherlands",
  140,      "140",                                "Houston Methodist Research Institute",                    "HMRI",                                                                    NA,          "USA",
  141,      "141",                                                 "Deventer Ziekenhuis",                "Deventer",                                                                    NA,  "Netherlands",
  142,      "142",                                           "Dayton Physicians Network",                  "Dayton",                                                                    NA,          "USA",
  143,      "143",                        "New Mexico Oncology & Hematology Consultants",                    "NMOH",                                                                    NA,          "USA",
  144,      "144",                    "NewYork–Presbyterian Brooklyn Methodist Hospital",  "NYP Brooklyn Methodist",                    "NewYork-Presbyterian Brooklyn Methodist Hospital",          "USA",
  145,      "145",                                           "Sligo University Hospital",                   "Sligo",                                           "Sligo University Hospital",      "Ireland",
  146,      "146",                                   "Instituto Valenciano de Oncologia",              "Valenciano",                                   "Instituto Valenciano de Oncologia",        "Spain",
  147,      "147",                                                       "Atrium Health",                  "Atrium",                                                                    NA,          "USA",
  148,      "148",                                                "James J. Peters VAMC",                "JJP VAMC",                                                                    NA,          "USA",
  149,      "149",                                       "Peter MacCallum Cancer Centre",               "MacCallum",                                       "Peter MacCallum Cancer Centre",    "Australia",
  150,      "150",                                            "Universitätsspital Basel",                   "Basel",                                            "Universitätsspital Basel",  "Switzerland",
  151,      "151",                                    "Ente Ospedaliero Cantonale (EOC)",                     "EOC",                                    "Ente Ospedaliero Cantonale (EOC)",  "Switzerland",
  152,      "152",                                           "Memphis VA Medical Center",              "Memphis VA",                                           "Memphis VA Medical Center",          "USA",
  153,      "153",                                               "University of Florida",                     "UFL",                                                                    NA,          "USA",
  154,      "154",                              "University of Ilorin Teaching Hospital",                    "UITH",                              "University of Ilorin Teaching Hospital",      "Nigeria",
  155,      "155",                            "Lagos State University Teaching Hospital",                    "LASU",                                                                    NA,      "Nigeria",
  156,      "156",                                     "Federal Medical Centre Abeokuta",            "FMC Abeokuta",                                     "Federal Medical Centre Abeokuta",      "Nigeria",
  157,      "157",                           "University of Maiduguri Teaching Hospital",                    "UMTH",                           "University of Maiduguri Teaching Hospital",      "Nigeria",
  158,      "158",                                    "Banner MD Anderson Cancer Center",                  "Banner",                                                                    NA,          "USA",
  159,      "159",                                        "Boca Raton Regional Hospital",                    "BRRH",                                                                    NA,          "USA",
  160,      "160",                                        "Medical College of Wisconsin",                     "MCW",                                                                    NA,          "USA",
  161,      "161",                                                        "SUNY Buffalo",                 "Buffalo",                                                                    NA,          "USA",
  162,      "162",                                  "Ralph H. Johnson VA Medical Center",                  "RHJ VA",                                  "Ralph H. Johnson VA Medical Center",          "USA",
  163,      "163",                                            "Durham VA Medical Center",               "Durham VA",                                                                    NA,          "USA",
  164,      "164",                                            "University of Cincinnati",             "UCincinnati",                                                                    NA,          "USA",
  165,      "165",                                     "Lahey Hospital & Medical Center",               "Lahey HMC",                                                                    NA,          "USA",
  166,      "166",                                            "Umeå University Hospital",                    "Umeå",                                            "Umeå University Hospital",       "Sweden",
  167,      "167",                                                 "Duke Cancer Network",                     "DCN",                                                 "Duke Cancer Network",          "USA",
  168,      "168",                             "Fox Chase Cancer Center – Temple Health",               "Fox Chase",                                                                    NA,          "USA",
  169,      "169",                            "VA of Western New York Healthcare System",           "VA Western NY",                                                                    NA,          "USA",
  170,      "170",                                            "Oslo University Hospital",                   "OsloU",                                                                    NA,       "Norway",
  171,      "171",                                             "St. Antonius Ziekenhuis",            "St. Antonius",                                                                    NA,  "Netherlands",
  172,      "172",                     "The University Of the West Indies – Mona Campus",                "UWI Mona",                                                                    NA,      "Jamaica",
  173,      "173",                            "University of Mississippi Medical Center",            "UMississippi",                            "University of Mississippi Medical Center",          "USA",
  174,      "174",                "Hematology Oncology Associates of the Treasure Coast",                   "HOATC",                                                                    NA,          "USA",
  175,      "175",                               "Mount Sinai Medical Center of Florida",                 "MSMC FL",                                                                    NA,          "USA",
  176,      "176",                                    "William Jennings Bryan Dorn VAMC",               "WJBD VAMC",                                                                    NA,          "USA",
  177,      "177",                                        "Tennessee Cancer Specialists",                     "TCS",                                                                    NA,          "USA",
  178,      "178",                                                  "New Jersey Urology",                     "NJU",                                                                    NA,          "USA",
  179,      "179",                                         "Nebraska Cancer Specialists",                     "NCS",                                                                    NA,          "USA",
  180,      "180",                     "Hospital Universitario Miguel Servet (Zaragoza)",                "Zaragoza",                     "Hospital Universitario Miguel Servet (Zaragoza)",        "Spain"
)

usethis::use_data(site_to_country, overwrite = TRUE)
