## code to prepare `treatment_map` dataset goes here
# ------------------------------------------------------------------------------
# INITIAL PARSING --------------------------------------------------------------
# This should not need to be executed again
# ------------------------------------------------------------------------------
library(tidyverse)

# datapasta::tribble_paste(treatment_map)
# from internal repository
# https://github.mskcc.org/pcctc/c16-170-ironman/blob/main/data-preparation/8-ironer-treatment-map.R

# ------------------------------------------------------------------------------
# END INITIAL PARSING ----------------------------------------------------------
# ------------------------------------------------------------------------------

treatment_map <-
  tibble::tribble(
    ~treatment,                                            ~treatment_lower,                  ~treatment_recode,            ~treatment_category, ~is_taxel, ~is_nha,
    "Casodex (bicalutamide)",                                    "casodex (bicalutamide)",                     "Bicalutamide",                          "ADT",     FALSE,   FALSE,
    "Nilandron (nilutamide)",                                    "nilandron (nilutamide)",                       "Nilutamide",                          "ADT",     FALSE,   FALSE,
    "Flutamide",                                                 "flutamide",                        "Flutamide",                          "ADT",     FALSE,   FALSE,
    "Degarelix",                                                 "degarelix",                        "Degarelix",                          "ADT",     FALSE,   FALSE,
    "Bicalutamide",                                              "bicalutamide",                     "Bicalutamide",                          "ADT",     FALSE,   FALSE,
    "Lupron",                                                    "lupron",                       "Leuprolide",                          "ADT",     FALSE,   FALSE,
    "Testosterone",                                              "testosterone",                     "Testosterone",                      "Steroid",     FALSE,   FALSE,
    "Zoladex (goserelin)",                                       "zoladex (goserelin)",                        "Goserelin",                          "ADT",     FALSE,   FALSE,
    "Leuprolide",                                                "leuprolide",                       "Leuprolide",                          "ADT",     FALSE,   FALSE,
    "Zometa",                                                    "zometa",                  "Zoledronic acid",              "Bisphosphonates",     FALSE,   FALSE,
    "CC-115",                                                    "cc-115",                           "CC-115", "mTOR kinase/DNA-PK Inhibitor",     FALSE,   FALSE,
    "Docetaxel",                                                 "docetaxel",                        "Docetaxel",                 "Chemotherapy",      TRUE,   FALSE,
    "Xgeva (denosumab)",                                         "xgeva (denosumab)",                        "Denosumab",         "Bone-Modifying Agent",     FALSE,   FALSE,
    "Triptorelin",                                               "triptorelin",                      "Triptorelin",                          "ADT",     FALSE,   FALSE,
    "Vantas (histrelin)",                                        "vantas (histrelin)",                        "Histrelin",                          "ADT",     FALSE,   FALSE,
    "Sipuleucel-T",                                              "sipuleucel-t",                     "Sipuleucel-T",                "Immunotherapy",     FALSE,   FALSE,
    "Trelstar",                                                  "trelstar",                      "Triptorelin",                          "ADT",     FALSE,   FALSE,
    "Leuprorelin",                                               "leuprorelin",                      "Leuprorelin",                          "ADT",     FALSE,   FALSE,
    "Prednisone",                                                "prednisone",                       "Prednisone",                      "Steroid",     FALSE,   FALSE,
    "Zytiga (abiraterone acetate)",                              "zytiga (abiraterone acetate)",              "Abiraterone Acetate",       "AR Signaling Inhibitor",     FALSE,    TRUE,
    "Xtandi (enzalutamide)",                                     "xtandi (enzalutamide)",                     "Enzalutamide",       "AR Signaling Inhibitor",     FALSE,    TRUE,
    "Dexamethasone",                                             "dexamethasone",                    "Dexamethasone",                      "Steroid",     FALSE,   FALSE,
    "Taxotere (docetaxel)",                                      "taxotere (docetaxel)",                        "Docetaxel",                 "Chemotherapy",      TRUE,   FALSE,
    "Cyproterone acetate",                                       "cyproterone acetate",              "Cyproterone acetate",                          "ADT",     FALSE,   FALSE,
    "Eligard (leuprolide)",                                      "eligard (leuprolide)",                       "Leuprolide",                          "ADT",     FALSE,   FALSE,
    "Decadron (dexamethasone)",                                  "decadron (dexamethasone)",                    "Dexamethasone",                      "Steroid",     FALSE,   FALSE,
    "Zoledronic acid",                                           "zoledronic acid",                  "Zoledronic acid",              "Bisphosphonates",     FALSE,   FALSE,
    "Firmagon (degarelix)",                                      "firmagon (degarelix)",                        "Degarelix",                          "ADT",     FALSE,   FALSE,
    "celecoxib",                                                 "celecoxib",                        "Celecoxib",              "COX-2 Inhibitor",     FALSE,   FALSE,
    "clinical trial with atorvastatin",                          "clinical trial with atorvastatin",                     "Atorvastatin",                  "Antilipemic",     FALSE,   FALSE,
    "Radium-223",                                                "radium-223",                       "Radium-223",         "Radiopharmaceuticals",     FALSE,   FALSE,
    "Enzalutamide",                                              "enzalutamide",                     "Enzalutamide",       "AR Signaling Inhibitor",     FALSE,    TRUE,
    "Abiraterone Acetate",                                       "abiraterone acetate",              "Abiraterone Acetate",       "AR Signaling Inhibitor",     FALSE,    TRUE,
    "Goserelin",                                                 "goserelin",                        "Goserelin",                          "ADT",     FALSE,   FALSE,
    "Denosumab",                                                 "denosumab",                        "Denosumab",         "Bone-Modifying Agent",     FALSE,   FALSE,
    "Cisplatin",                                                 "cisplatin",                        "Cisplatin",                 "Chemotherapy",     FALSE,   FALSE,
    "Etoposide",                                                 "etoposide",                        "Etoposide",                 "Chemotherapy",     FALSE,   FALSE,
    "Spironolactone",                                            "spironolactone",                   "Spironolactone",                          "ADT",     FALSE,   FALSE,
    "Buserelin",                                                 "buserelin",                        "Buserelin",                          "ADT",     FALSE,   FALSE,
    "Ketoconazole",                                              "ketoconazole",                     "Ketoconazole",                          "ADT",     FALSE,   FALSE,
    "Leukine (sargramostim)",                                    "leukine (sargramostim)",                     "Sargramostim",                "Immunotherapy",     FALSE,   FALSE,
    "Muscadine MPX",                                             "muscadine mpx",                    "Muscadine MPX",                "Nutraceutical",     FALSE,   FALSE,
    "Nilutamide",                                                "nilutamide",                       "Nilutamide",                          "ADT",     FALSE,   FALSE,
    "Anandron",                                                  "anandron",                       "Nilutamide",                          "ADT",     FALSE,   FALSE,
    "chemotherapy",                                              "chemotherapy",                     "Chemotherapy",                 "Chemotherapy",     FALSE,   FALSE,
    "Carboplatin",                                               "carboplatin",                      "Carboplatin",                 "Chemotherapy",     FALSE,   FALSE,
    "Cyprostat (cyproterone acetate)",                           "cyprostat (cyproterone acetate)",              "Cyproterone acetate",                          "ADT",     FALSE,   FALSE,
    "Androgen Deprivation Therapy (ADT), unspecified",           "androgen deprivation therapy (adt), unspecified",                              "ADT",                          "ADT",     FALSE,   FALSE,
    "BCG",                                                       "bcg",                              "BCG",                "Immunotherapy",     FALSE,   FALSE,
    "Muscadine MPX/Placebo",                                     "muscadine mpx/placebo",            "Muscadine MPX/Placebo",        "Nutraceutical/Placebo",     FALSE,   FALSE,
    "Paraplatin (carboplatin)",                                  "paraplatin (carboplatin)",                      "Carboplatin",                 "Chemotherapy",     FALSE,   FALSE,
    "Prolia (denosumab)",                                        "prolia (denosumab)",                        "Denosumab",         "Bone-Modifying Agent",     FALSE,   FALSE,
    "Xofigo (Radium-223)",                                       "xofigo (radium-223)",                       "Radium-223",         "Radiopharmaceuticals",     FALSE,   FALSE,
    "Relugolix",                                                 "relugolix",                        "Relugolix",                          "ADT",     FALSE,   FALSE,
    "Eulexin (flutamide)",                                       "eulexin (flutamide)",                        "Flutamide",                          "ADT",     FALSE,   FALSE,
    "Androcur (cyproterone acetate)",                            "androcur (cyproterone acetate)",              "Cyproterone acetate",                          "ADT",     FALSE,   FALSE,
    "Prostap (leuprorelin)",                                     "prostap (leuprorelin)",                      "Leuprorelin",                          "ADT",     FALSE,   FALSE,
    "Depo-Provera (medroxyprogesterone acetate)",                "depo-provera (medroxyprogesterone acetate)",              "Medroxyprogesterone",                 "Progesterone",     FALSE,   FALSE,
    "Cabazitaxel",                                               "cabazitaxel",                      "Cabazitaxel",                 "Chemotherapy",      TRUE,   FALSE,
    "risedronate",                                               "risedronate",                      "Risedronate",              "Bisphosphonates",     FALSE,   FALSE,
    "Olaparib",                                                  "olaparib",                         "Olaparib",                         "PARP",     FALSE,   FALSE,
    "Decapeptyl (triptorelin)",                                  "decapeptyl (triptorelin)",                      "Triptorelin",                          "ADT",     FALSE,   FALSE,
    "Metformin",                                                 "metformin",                        "Metformin",                 "Antidiabetic",     FALSE,   FALSE,
    "Darolutamide (ODM-201)/Placebo",                            "darolutamide (odm-201)/placebo",   "Darolutamide (ODM-201)/Placebo",       "AR Signaling Inhibitor",     FALSE,    TRUE,
    "Prednisolone",                                              "prednisolone",                     "Prednisolone",                      "Steroid",     FALSE,   FALSE,
    "Tamoxifen",                                                 "tamoxifen",                        "Tamoxifen",                 "Chemotherapy",     FALSE,   FALSE,
    "LHRHa",                                                     "lhrha",                              "ADT",                          "ADT",     FALSE,   FALSE,
    "Prednisol (prednisolone)",                                  "prednisol (prednisolone)",                     "Prednisolone",                      "Steroid",     FALSE,   FALSE,
    "LHRH",                                                      "lhrh",                              "ADT",                          "ADT",     FALSE,   FALSE,
    "Pentostatin",                                               "pentostatin",                      "Pentostatin",                 "Chemotherapy",     FALSE,   FALSE,
    "Ipilimumab (MDX-010)",                                      "ipilimumab (mdx-010)",             "Ipilimumab (MDX-010)",                "Immunotherapy",     FALSE,   FALSE,
    "androgen suppression",                                      "androgen suppression",                              "ADT",                          "ADT",     FALSE,   FALSE,
    "Apalutamide",                                               "apalutamide",                      "Apalutamide",       "AR Signaling Inhibitor",     FALSE,    TRUE,
    "LH-RHagonist (unspecified)",                                "lh-rhagonist (unspecified)",                              "ADT",                          "ADT",     FALSE,   FALSE,
    "Nivolumab",                                                 "nivolumab",                        "Nivolumab",                "Immunotherapy",     FALSE,   FALSE,
    "Pembrolizumab/Placebo",                                     "pembrolizumab/placebo",            "Pembrolizumab/Placebo",        "Immunotherapy/Placebo",     FALSE,   FALSE,
    "LHRH agonist",                                              "lhrh agonist",                     "LHRH agonist",                          "ADT",     FALSE,   FALSE,
    "R-CHOP",                                                    "r-chop",                     "Chemotherapy",                 "Chemotherapy",     FALSE,   FALSE,
    "Capecitabine",                                              "capecitabine",                     "Capecitabine",                 "Chemotherapy",     FALSE,   FALSE,
    "Oxaliplatin",                                               "oxaliplatin",                      "Oxaliplatin",                 "Chemotherapy",     FALSE,   FALSE,
    "Hormone therapy",                                           "hormone therapy",                              "ADT",                          "ADT",     FALSE,   FALSE,
    "Ipatasertib",                                               "ipatasertib",                      "Ipatasertib",                "Akt Inhibitor",     FALSE,   FALSE,
    "Rucaparib",                                                 "rucaparib",                        "Rucaparib",                         "PARP",     FALSE,   FALSE,
    "Metformin (clinical trial)",                                "metformin (clinical trial)",                        "Metformin",                 "Antidiabetic",     FALSE,   FALSE,
    "Duodart (dutasteride/tamsulosina)",                         "duodart (dutasteride/tamsulosina)",                      "Dutasteride",                          "ADT",     FALSE,   FALSE,
    "Pembrolizumab",                                             "pembrolizumab",                    "Pembrolizumab",                "Immunotherapy",     FALSE,   FALSE,
    "GnRH analog",                                               "gnrh analog",                      "GnRH analog",                          "ADT",     FALSE,   FALSE,
    "Darolutamide (ODM-201)",                                    "darolutamide (odm-201)",           "Darolutamide (ODM-201)",       "AR Signaling Inhibitor",     FALSE,    TRUE,
    "Finasteride",                                               "finasteride",                            "Other",                        "Other",     FALSE,   FALSE,
    "ibandronic acid",                                           "ibandronic acid",                      "Ibandronate",              "Bisphosphonates",     FALSE,   FALSE,
    "Androgen deprivation LHRH",                                 "androgen deprivation lhrh",                              "ADT",                          "ADT",     FALSE,   FALSE,
    "Estradiol",                                                 "estradiol",                        "Estradiol",                          "ADT",     FALSE,   FALSE,
    "Taxol (paclitaxel)",                                        "taxol (paclitaxel)",                       "Paclitaxel",                 "Chemotherapy",      TRUE,   FALSE,
    "Ibandronic Acid",                                           "ibandronic acid",                      "Ibandronate",              "Bisphosphonates",     FALSE,   FALSE,
    "cemiplimab",                                                "cemiplimab",                       "Cemiplimab",                "Immunotherapy",     FALSE,   FALSE,
    "Suprefact (buserelin)",                                     "suprefact (buserelin)",                        "Buserelin",                          "ADT",     FALSE,   FALSE,
    "Yervoy",                                                    "yervoy",             "Ipilimumab (MDX-010)",                "Immunotherapy",     FALSE,   FALSE,
    "Keytruda",                                                  "keytruda",                    "Pembrolizumab",                "Immunotherapy",     FALSE,   FALSE,
    "ipatasertib/placebo",                                       "ipatasertib/placebo",              "Ipatasertib/Placebo",        "Akt Inhibitor/Placebo",     FALSE,   FALSE,
    "Mifepristone",                                              "mifepristone",                     "Mifepristone",                      "Steroid",     FALSE,   FALSE,
    "Exicorilant (CORT 125281)",                                 "exicorilant (cort 125281)",        "Exicorilant (CORT 125281)",                "GR Antagonist",     FALSE,   FALSE,
    "AZD8186",                                                   "azd8186",                          "AZD8186",               "PI3K Inhibitor",     FALSE,   FALSE,
    "Galunisertib (LY2157299)",                                  "galunisertib (ly2157299)",         "Galunisertib (LY2157299)",     "TGF-ßRI Kinase Inhibitor",     FALSE,   FALSE,
    "Lutetium-177",                                              "lutetium-177",                     "Lutetium-177",         "Radiopharmaceuticals",     FALSE,   FALSE,
    "CPI-1205",                                                  "cpi-1205",                         "CPI-1205",               "EZH2 Inhibitor",     FALSE,   FALSE,
    "Niraparib",                                                 "niraparib",                        "Niraparib",                         "PARP",     FALSE,   FALSE,
    "Adavosertib (AZD1775)",                                     "adavosertib (azd1775)",            "Adavosertib (AZD1775)",               "Wee1 Inhibitor",     FALSE,   FALSE,
    "Niraparib/Placebo",                                         "niraparib/placebo",                "Niraparib/Placebo",                 "PARP/Placebo",     FALSE,   FALSE,
    "VERU-111",                                                  "veru-111",                         "VERU-111",        "α/β Tubulin Inhibitor",     FALSE,   FALSE,
    "Placebo/Ipatasertib",                                       "placebo/ipatasertib",              "Ipatasertib/Placebo",        "Akt Inhibitor/Placebo",     FALSE,   FALSE,
    "Olaparib/Placebo",                                          "olaparib/placebo",                 "Olaparib/Placebo",                 "PARP/Placebo",     FALSE,   FALSE,
    "PSMA-Ligand",                                               "psma-ligand",                    "Immunotherapy",                "Immunotherapy",     FALSE,   FALSE,
    "Onvansertib (PCM-075)",                                     "onvansertib (pcm-075)",            "Onvansertib (PCM-075)",               "PLK1 Inhibitor",     FALSE,   FALSE,
    "Cyclophosphamide",                                          "cyclophosphamide",                 "Cyclophosphamide",                 "Chemotherapy",     FALSE,   FALSE,
    "Meformin",                                                  "meformin",                        "Metformin",                 "Antidiabetic",     FALSE,   FALSE,
    "Metfomin",                                                  "metfomin",                        "Metformin",                 "Antidiabetic",     FALSE,   FALSE,
    "Ribociclib",                                                "ribociclib",                       "Ribociclib",                "CDK Inhibitor",     FALSE,   FALSE,
    "Durvalumab",                                                "durvalumab",                       "Durvalumab",                "Immunotherapy",     FALSE,   FALSE,
    "225Ac-J591",                                                "225ac-j591",                       "225Ac-J591",         "Radiopharmaceuticals",     FALSE,   FALSE,
    "Talazoparib",                                               "talazoparib",                      "Talazoparib",                         "PARP",     FALSE,   FALSE,
    "JNJ-63898081",                                              "jnj-63898081",                     "JNJ-63898081",                "Immunotherapy",     FALSE,   FALSE,
    "Ceralasertib (AZD6738)",                                    "ceralasertib (azd6738)",           "Ceralasertib (AZD6738)",         "ATR Kinase Inhibitor",     FALSE,   FALSE,
    "Abemaciclib",                                               "abemaciclib",                      "Abemaciclib",                "CDK Inhibitor",     FALSE,   FALSE,
    "Talazoparib/Placebo",                                       "talazoparib/placebo",              "Talazoparib/Placebo",                 "PARP/Placebo",     FALSE,   FALSE,
    "ESK981",                                                    "esk981",                           "ESK981",       "Multi-kinase Inhibitor",     FALSE,   FALSE,
    "Epirubicin",                                                "epirubicin",                       "Epirubicin",                 "Chemotherapy",     FALSE,   FALSE,
    "Fluorouracil",                                              "fluorouracil",                     "Fluorouracil",                 "Chemotherapy",     FALSE,   FALSE,
    "Actinium-225-PSMA-617",                                     "actinium-225-psma-617",                     "Actinium-225",         "Radiopharmaceuticals",     FALSE,   FALSE,
    "bispecific antibody armed activated t cell clinical trial", "bispecific antibody armed activated t cell clinical trial",                    "Immunotherapy",                "Immunotherapy",     FALSE,   FALSE,
    "Metformin (as part of STAMPEDE trial)",                     "metformin (as part of stampede trial)",                        "Metformin",                 "Antidiabetic",     FALSE,   FALSE,
    "Molibresib (GSK525762)",                                    "molibresib (gsk525762)",           "Molibresib (GSK525762)",                "BET Inhibitor",     FALSE,   FALSE,
    "Clinical trial",                                            "clinical trial",                            "Other",                        "Other",     FALSE,   FALSE,
    "Abemaciclib/Placebo",                                       "abemaciclib/placebo",              "Abemaciclib/Placebo",        "CDK Inhibitor/Placebo",     FALSE,   FALSE,
    "ascorbic Acid/placebo",                                     "ascorbic acid/placebo",                "Vitamin C/Placebo",               "Nutraceuticals",     FALSE,   FALSE,
    "Spartalizumab (PDR001)",                                    "spartalizumab (pdr001)",           "Spartalizumab (PDR001)",                "Immunotherapy",     FALSE,   FALSE,
    "Atezolizumab",                                              "atezolizumab",                     "Atezolizumab",                "Immunotherapy",     FALSE,   FALSE,
    "Xeloda (capecitabine)",                                     "xeloda (capecitabine)",                     "Capecitabine",                 "Chemotherapy",     FALSE,   FALSE,
    "Immunotherapy investigational trial",                       "immunotherapy investigational trial",                    "Immunotherapy",                "Immunotherapy",     FALSE,   FALSE,
    "Capivasertib/Placebo",                                      "capivasertib/placebo",             "Capivasertib/Placebo",        "Akt Inhibitor/Placebo",     FALSE,   FALSE,
    "Clinical Trial",                                            "clinical trial",                            "Other",                        "Other",     FALSE,   FALSE,
    "Endoxana (cyclophosphamide)",                               "endoxana (cyclophosphamide)",                 "Cyclophosphamide",                 "Chemotherapy",     FALSE,   FALSE,
    "Capivasertib (AZD5363)",                                    "capivasertib (azd5363)",           "Capivasertib (AZD5363)",                "Akt Inhibitor",     FALSE,   FALSE,
    "ARV-110",                                                   "arv-110",                          "ARV-110",       "AR Signaling Inhibitor",     FALSE,   FALSE,
    "CCS1477-M (trial)",                                         "ccs1477-m (trial)",                          "CCS1477",        "Bromodomain Inhibitor",     FALSE,   FALSE,
    "Paclitaxel",                                                "paclitaxel",                       "Paclitaxel",                 "Chemotherapy",      TRUE,   FALSE,
    "Cabozantinib",                                              "cabozantinib",                     "Cabozantinib",                 "Chemotherapy",     FALSE,   FALSE,
    "CPT-11",                                                    "cpt-11",                           "CPT-11",                 "Chemotherapy",     FALSE,   FALSE,
    "Gemcitabine",                                               "gemcitabine",                      "Gemcitabine",                 "Chemotherapy",     FALSE,   FALSE,
    "RLY-1971",                                                  "rly-1971",                         "RLY-1971",               "SHP2 Inhibitor",     FALSE,   FALSE,
    "AR-110",                                                    "ar-110",                          "ARV-110",       "AR Signaling Inhibitor",     FALSE,   FALSE,
    "NIR178",                                                    "nir178",                           "NIR178",               "A2AR Inhibitor",     FALSE,   FALSE,
    "pTVG-HP",                                                   "ptvg-hp",                    "Immunotherapy",                "Immunotherapy",     FALSE,   FALSE,
    "Phase 1 clinical trial drug",                               "phase 1 clinical trial drug",                            "Other",                        "Other",     FALSE,   FALSE,
    "Palbociclib",                                               "palbociclib",                      "Palbociclib",                "CDK Inhibitor",     FALSE,   FALSE,
    "unknown LHRH agonist",                                      "unknown lhrh agonist",                              "ADT",                          "ADT",     FALSE,   FALSE,
    "Actinium-225",                                              "actinium-225",                     "Actinium-225",         "Radiopharmaceuticals",     FALSE,   FALSE,
    "PT-112",                                                    "pt-112",                           "PT-112",                "Immunotherapy",     FALSE,   FALSE,
    "Erleada (apalutamide)",                                     "erleada (apalutamide)",                      "Apalutamide",       "AR Signaling Inhibitor",     FALSE,    TRUE,
    "Orgovyx",                                                   "orgovyx",                        "Relugolix",                          "ADT",     FALSE,   FALSE,
    "Provenge",                                                  "provenge",                     "Sipuleucel-T",                "Immunotherapy",     FALSE,   FALSE,
    "Nubeqa",                                                    "nubeqa",           "Darolutamide (ODM-201)",       "AR Signaling Inhibitor",     FALSE,    TRUE,
    "Procarbazine",                                              "procarbazine",                     "Procarbazine",                 "Chemotherapy",     FALSE,   FALSE,
    "Enzalutamide/Placebo",                                      "enzalutamide/placebo",             "Enzalutamide/Placebo",       "AR Signaling Inhibitor",     FALSE,    TRUE,
    "Mitoxantrone",                                              "mitoxantrone",                     "Mitoxantrone",                 "Chemotherapy",     FALSE,   FALSE,
    "Poly ICLC",                                                 "poly iclc",                        "Poly ICLC",                "Immunotherapy",     FALSE,   FALSE,
    "Jevtana",                                                   "jevtana",                      "Cabazitaxel",                 "Chemotherapy",      TRUE,   FALSE,
    "Stilboestrol (diethylstilbestrol)",                         "stilboestrol (diethylstilbestrol)",               "Diethylstilbestrol",                          "ADT",     FALSE,   FALSE,
    "Vipivotide tetraxetan (PSMA-617)",                          "vipivotide tetraxetan (psma-617)", "Vipivotide tetraxetan (PSMA-617)",         "Radiopharmaceuticals",     FALSE,   FALSE,
    "Ascorbic Acid/Placebo",                                     "ascorbic acid/placebo",                "Vitamin C/Placebo",               "Nutraceuticals",     FALSE,   FALSE
  ) |>
  labelled::set_variable_labels(
    treatment = "Treatment as entered",
    treatment_lower = "Treatment as entered lower case",
    treatment_category = "Assigned treatment category",
    treatment_recode = "Assigned treatment standardized coding",
    is_taxel = "Treatment is one of  Cabazitaxel, Docetaxel, Paclitaxel, Tesetaxel",
    is_nha = "Treatment is a novel hormonal agent (one of Abiraterone, Enzalutamide, Darolutamide, Apalutamide)"
  )




usethis::use_data(treatment_map, overwrite = TRUE)
