## code to prepare `treatment_map` dataset goes here
# ------------------------------------------------------------------------------
# INITIAL PARSING --------------------------------------------------------------
# This should not need to be executed again
# ------------------------------------------------------------------------------
library(tidyverse)

trt_classification_path <- pcctc::ae_synonyms_path()

trt_class <- readxl::read_xlsx(
  trt_classification_path,
  sheet = "TxClassification",
  range = readxl::cell_cols("A:C")
)

trt_syn <- readxl::read_xlsx(
  trt_classification_path,
  sheet = "TxSynonyms",
  range = readxl::cell_cols("A:C")
)

# converting treatment ignore assigments to treatment other assignments
trt_other <- readxl::read_xlsx(
  trt_classification_path,
  sheet = "TxIgnore",
  range = readxl::cell_cols("A")
) %>%
  dplyr::mutate(
    `LkpCode Combined` = "Other",
    MedCategory = "Other"
  )

treatment_map <- dplyr::bind_rows(trt_class, trt_syn, trt_other) %>%
  dplyr::rename(
    treatment = .data$LkpCode,
    treatment_std = .data$`LkpCode Combined`,
    treatment_category = .data$MedCategory
  ) %>%
  dplyr::mutate(
    treatment_recode = dplyr::coalesce(.data$treatment_std, .data$treatment_category)
  ) %>%
  dplyr::select(treatment_category, treatment_recode, treatment) %>%
  dplyr::arrange(treatment_category, treatment_recode, treatment)


# *** Note: Stilboestrol (diethylstilbetrol) -- ADT is in ironer::adt_steroid but not trt map
check <- ironer::adt_steroid %>%
  mutate(treatment = stringr::str_to_lower(TREATMENT)) %>%
  full_join(treatment_map, by = "treatment")


# environment setting
datapasta::dp_set_max_rows(1000)
# create inline data
datapasta::tribble_paste(treatment_map)


# ------------------------------------------------------------------------------
# END INITIAL PARSING ----------------------------------------------------------
# ------------------------------------------------------------------------------
library(tidyverse)

treatment_map <- tibble::tribble(
  ~treatment_category,                        ~treatment_recode,                                                                  ~treatment,
  "a/ß tubulin inhibitor",                               "VERU-111",                                           "VERU-111 (Α/Β TUBULIN INHIBITOR",
  "a/ß tubulin inhibitor",                               "VERU-111",                                         "VERU-111 (О±/ОІ tubulin inhibitor",
  "a/ß tubulin inhibitor",                               "VERU-111",                                                    "VERU 111 (Oral Taxane)",
  "a/ß tubulin Inhibitor",                               "VERU-111",                                                                  "VERU-111",
  "A2AR Inhibitor",                                "AZD4635",                                                                   "AZD4635",
  "A2AR Inhibitor",                                 "NIR178",                                                                   "NIR 178",
  "A2AR Inhibitor",                                 "NIR178",                                                                    "NIR178",
  "ADT",                                    "ADT",                                                                       "ADT",
  "ADT",                                    "ADT",                                                       "ADT - unknown agent",
  "ADT",                                    "ADT",                                                              "ADT + Lupron",
  "ADT",                                    "ADT",                                                              "ADT, unknown",
  "ADT",                                    "ADT",                                                 "Androgen deprivation LHRH",
  "ADT",                                    "ADT",                                              "Androgen Deprivation Therapy",
  "ADT",                                    "ADT",                           "Androgen Deprivation Therapy (ADT), unspecified",
  "ADT",                                    "ADT",                                                      "androgen suppression",
  "ADT",                                    "ADT",                                                     "CAB with bicalutamide",
  "ADT",                                    "ADT",                                                     "CAB with enzalutamide",
  "ADT",                                    "ADT",                                                   "Firmagon and Leuprolide",
  "ADT",                                    "ADT",                                                                       "HDT",
  "ADT",                                    "ADT",                                                                   "hormone",
  "ADT",                                    "ADT",                                                           "Hormone Therapy",
  "ADT",                                    "ADT",                                                     "Hormone Therapy (ADT)",
  "ADT",                                    "ADT",                                                 "Hormone therapy in Canada",
  "ADT",                                    "ADT",                                                      "Hormone/Gnrh agonist",
  "ADT",                                    "ADT",                                                "LH-RHagonist (unspecified)",
  "ADT",                                    "ADT",                                                                      "LHRH",
  "ADT",                                    "ADT",                                                                    "LHRH-A",
  "ADT",                                    "ADT",                                                                     "LHRHa",
  "ADT",                                    "ADT",                                                          "Lupron & Casodex",
  "ADT",                                    "ADT",                                              "UNKNOWN ANDROGEN DEPRIVATION",
  "ADT",                                    "ADT",                                                      "unknown LHRH agonist",
  "ADT",                      "Aminoglutethimide",                                                         "Aminoglutethimide",
  "ADT",                           "Bicalutamide",                                                              "Bicalutamide",
  "ADT",                           "Bicalutamide",                                                    "Casodex (bicalutamide)",
  "ADT",                              "Buserelin",                                                                 "Buserelin",
  "ADT",                              "Buserelin",                                                     "Suprefact (buserelin)",
  "ADT",                    "Cyproterone acetate",                                            "Androcur (cyproterone acetate)",
  "ADT",                    "Cyproterone acetate",                                           "Cyprostat (cyproterone acetate)",
  "ADT",                    "Cyproterone acetate",                                                       "Cyproterone acetate",
  "ADT",           "Cytadren (aminoglutethimide)",                                              "Cytadren (aminoglutethimide)",
  "AR Signaling Inhibitor",                 "Darolutamide (ODM-201)",                                                                    "Nubeqa",
  "ADT",                              "Degarelix",                                                                 "Degarelix",
  "ADT",                              "Degarelix",                                                      "Firmagon (degarelix)",
  "ADT",                             "Deslorelin",                                                                "Deslorelin",
  "ADT",                     "Diethylstilbestrol",                                               "Apstil (diethylstilbestrol)",
  "ADT",                     "Diethylstilbestrol",                                                  "DES (diethylstilbestrol)",
  "ADT",                     "Diethylstilbestrol",                                                        "Diethylstilbestrol",
  "ADT",                     "Diethylstilbestrol",                                         "Stilboestrol (diethylstilbestrol)",
  "ADT",                            "Dutasteride",                                         "Duodart (dutasteride/tamsulosina)",
  "ADT",                              "Estradiol",                                                                 "Estradiol",
  "ADT",                              "Estradiol",                                                    "transdermal oestradiol",
  "ADT",                              "Flutamide",                                                      "Drogenil (flutamide)",
  "ADT",                              "Flutamide",                                                        "Euflex (flutamide)",
  "ADT",                              "Flutamide",                                                       "Eulexin (flutamide)",
  "ADT",                              "Flutamide",                                                                 "Flutamide",
  "ADT",                 "Fosfestrol tetrasodium",                                                    "Fosfestrol tetrasodium",
  "ADT",                            "GnRH analog",                                                               "GnRH analog",
  "ADT",                              "Goserelin",                                                                 "Goserelin",
  "ADT",                              "Goserelin",                                                       "Zoladex (goserelin)",
  "ADT",                                 "HE3235",                                                                    "HE3235",
  "ADT",                              "Histrelin",                                                                 "Histrelin",
  "ADT",                              "Histrelin",                                                  "Supprelin LA (histrelin)",
  "ADT",                              "Histrelin",                                                        "Vantas (histrelin)",
  "ADT",        "Honvan (fosfestrol tetrasodium)",                                           "Honvan (fosfestrol tetrasodium)",
  "ADT",                           "Itraconazole",                                                              "Itraconazole",
  "ADT",                           "Ketoconazole",                                                                    "Extina",
  "ADT",                           "Ketoconazole",                                                              "Ketoconazole",
  "ADT",                           "Ketoconazole",                                                    "Nizoral (ketoconazole)",
  "ADT",                           "Ketoconazole",                                                                   "Xolegel",
  "ADT",                             "Leuprolide",                                                                   "Eligard",
  "ADT",                             "Leuprolide",                                                      "Eligard (leuprolide)",
  "ADT",                             "Leuprolide",                                                                "Leuprolide",
  "ADT",                             "Leuprolide",                                                        "leuprolide acetate",
  "ADT",                             "Leuprolide",                                                                    "Lupron",
  "ADT",                             "Leuprolide",                                                                    "Viadur",
  "ADT",                            "Leuprorelin",                                                     "Enantone (Leuproelin)",
  "ADT",                            "Leuprorelin",                                                               "Leuprorelin",
  "ADT",                            "Leuprorelin",                                                     "Prostap (leuprorelin)",
  "ADT",                           "LHRH agonist",                                                              "LHRH agonist",
  "ADT",                              "Nafarelin",                                                                 "Nafarelin",
  "ADT",                             "Nilutamide",                                                                  "Anandron",
  "ADT",                             "Nilutamide",                                                    "Nilandron (nilutamide)",
  "ADT",                             "Nilutamide",                                                                "Nilutamide",
  "ADT",           "Orimeten (aminoglutethimide)",                                              "Orimeten (aminoglutethimide)",
  "ADT",                             "Raloxifene",                                                                "Raloxifene",
  "ADT",               "Raloxifene hydrochloride",                                         "EVISTA (raloxifene hydrochloride)",
  "ADT",                              "Relugolix",                                                                   "Orgovyx",
  "ADT",                              "Relugolix",                                                                 "regulorix",
  "ADT",                              "Relugolix",                                                                 "Relugolix",
  "ADT",                         "Spironolactone",                                                "Spiroctan (spironolactone)",
  "ADT",                         "Spironolactone",                                                            "Spironolactone",
  "ADT",                           "Stilphostrol",                                                              "Stilphostrol",
  "ADT",                               "Suprecur",                                                                  "Suprecur",
  "ADT",                                "TAS3681",                                                                   "TAS3681",
  "ADT",                            "Triptorelin",                                                 "De-capeptyl (triptorelin)",
  "ADT",                            "Triptorelin",                                                  "Decapeptyl (triptorelin)",
  "ADT",                            "Triptorelin",                                                                  "Trelstar",
  "ADT",                            "Triptorelin",                                                               "Triptorelin",
  "ADT",                            "Unknown ADT",                                                               "UNKNOWN ADT",
  "Akt Inhibitor",                 "Capivasertib (AZD5363)",                                                    "Capivasertib (AZD5363)",
  "Akt Inhibitor",                            "Ipatasertib",                                                               "Ipatasertib",
  "Akt Inhibitor",                    "Ipatasertib/Placebo",                                                          "GDC-0068/Placebo",
  "Akt Inhibitor/Placebo",                   "Capivasertib/Placebo",                                                      "Capivasertib/Placebo",
  "Akt Inhibitor/Placebo",                    "Ipatasertib/Placebo",                                                       "Ipatasertib/Placebo",
  "Akt Inhibitor/Placebo",                    "Ipatasertib/Placebo",                                                       "Placebo/Ipatasertib",
  "Aldehyde Dehydrogenase Inhibitor",                             "Disulfiram",                                                                "Disulfiram",
  "Angiogenesis Inhibitor",                            "Angiostatin",                                                               "Angiostatin",
  "Angiogenesis Inhibitor",                            "Thalidomide",                                                               "Thalidomide",
  "Antidiabetic",                              "Metformin",                                                                  "Meformin",
  "Antidiabetic",                              "Metformin",                                                                  "Metfomin",
  "Antidiabetic",                              "Metformin",                                                                 "Metformin",
  "Antidiabetic",                              "Metformin",                                     "Metformin (as part of STAMPEDE trial)",
  "Antidiabetic",                              "Metformin",                                                "Metformin (clinical trial)",
  "Antilipemic",                           "Atorvastatin",                                          "clinical trial with atorvastatin",
  "Antimetabolite",                              "Exisulind",                                                                 "Exisulind",
  "AR Signaling Inhibitor",                    "Abiraterone Acetate",                                                       "Abiraterone Acetate",
  "AR Signaling Inhibitor",                    "Abiraterone Acetate",                                                                     "Yonsa",
  "AR Signaling Inhibitor",                    "Abiraterone Acetate",                                              "Zytiga (abiraterone acetate)",
  "AR Signaling Inhibitor",                            "Apalutamide",                                                               "Apalutamide",
  "AR Signaling Inhibitor",                            "Apalutamide",                                                                   "ARN-509",
  "AR Signaling Inhibitor",                            "Apalutamide",                                                                   "Erleada",
  "AR Signaling Inhibitor",                            "Apalutamide",                                                     "Erleada (apalutamide)",
  "AR Signaling Inhibitor",                            "Apalutamide",                                                    "JNJ-56021927 (ARN-509)",
  "AR Signaling Inhibitor",                                "ARV-110",                                                                    "AR-110",
  "AR Signaling Inhibitor",                                "ARV-110",                                                                   "ARV-110",
  "AR Signaling Inhibitor",                                 "ASN001",                                                                    "ASN001",
  "AR Signaling Inhibitor",                 "Darolutamide (ODM-201)",                                                              "Darolutamide",
  "AR Signaling Inhibitor",                 "Darolutamide (ODM-201)",                                                    "Darolutamide (ODM-201)",
  "AR Signaling Inhibitor",         "Darolutamide (ODM-201)/Placebo",                         "Darolutamide (ODM-201) OR PLACEBO (ARASENS STUDY)",
  "AR Signaling Inhibitor",         "Darolutamide (ODM-201)/Placebo",                                            "Darolutamide (ODM-201)/Placebo",
  "AR Signaling Inhibitor",                           "Enzalutamide",                                                              "Enzalutamide",
  "AR Signaling Inhibitor",                           "Enzalutamide",                              "Enzalutamide for Enza + cc115 Clinical Trial",
  "AR Signaling Inhibitor",                           "Enzalutamide",                                                              "Enzatulamide",
  "AR Signaling Inhibitor",                           "Enzalutamide",                                                     "Xtandi (enzalutamide)",
  "AR Signaling Inhibitor",                   "Enzalutamide/Placebo",                                                      "Enzalutamide/Placebo",
  "AR Signaling Inhibitor",                                "FT-7051",                                                                   "FT-7051",
  "AR Signaling Inhibitor",                   "Galeterone (TOK-001)",                                                      "Galeterone (TOK-001)",
  "AR Signaling Inhibitor",                    "Orteronel (TAK-700)",                                                       "Orteronel (TAK-700)",
  "AR Signaling Inhibitor",                          "Proxalutamide",                                                             "Proxalutamide",
  "AR Signaling Inhibitor",                                 "VT-464",                                                                    "VT-464",
  "AR Signaling Inhibitor/Placebo",            "Abiraterone Acetate/Placebo",                                               "Abiraterone Acetate/Placebo",
  "AR Signaling Inhibitor/Placebo",                    "Apalutamide/Placebo",                                                           "ARN-509/Placebo",
  "ATR kinase inhibitor",                 "Ceralasertib (AZD6738)",                                                                   "AZD6738",
  "ATR kinase Inhibitor",                 "Ceralasertib (AZD6738)",                                                    "Ceralasertib (AZD6738)",
  "Aurora A and TRK inhibitor",                                "TAS-119",                                                                   "TAS-119",
  "BET Inhibitor",                          "BET Inhibitor",                                                             "BET-inhibitor",
  "BET Inhibitor",                                "GS-5829",                                                                   "GS-5829",
  "BET Inhibitor",                 "Molibresib (GSK525762)",                                                                 "GSK525762",
  "BET Inhibitor",                 "Molibresib (GSK525762)",                                                    "Molibresib (GSK525762)",
  "BET Inhibitor",                              "ZEN003694",                                                                 "ZEN003694",
  "Bisphosphonates",                            "Ibandronate",                                                           "ibandronic acid",
  "Bisphosphonates",                            "Risedronate",                                                               "Risedronate",
  "Bisphosphonates",                        "Zoledronic acid",                                                               "Zoledronate",
  "Bisphosphonates",                        "Zoledronic acid",                                                           "Zoledronic acid",
  "Bisphosphonates",                        "Zoledronic acid",                                                                    "Zometa",
  "Bone-Modifying Agent",                              "Denosumab",                                                                 "Denosumab",
  "Bone-Modifying Agent",                              "Denosumab",                                                                    "Prolia",
  "Bone-Modifying Agent",                              "Denosumab",                                                        "Prolia (denosumab)",
  "Bone-Modifying Agent",                              "Denosumab",                                                                     "Xgeva",
  "Bone-Modifying Agent",                              "Denosumab",                                                         "Xgeva (denosumab)",
  "Bromodomain Inhibitor",                                "CCS1477",                                                         "CCS1477-M (trial)",
  "CDK Inhibitor",                            "Abemaciclib",                                                               "Abemaciclib",
  "CDK Inhibitor",                            "Palbociclib",                                                               "Palbociclib",
  "CDK Inhibitor",                             "Ribociclib",                                                                "Ribociclib",
  "CDK Inhibitor/Placebo",                    "Abemaciclib/Placebo",                                                    "Abemaciclib or Placebo",
  "CDK Inhibitor/Placebo",                    "Abemaciclib/Placebo",                                                       "Abemaciclib/Placebo",
  "CDK Inhibitor/Placebo",                    "Abemaciclib/Placebo",                                                    "ID-abemaciclib/placebo",
  "CDK Inhibitor; AR Signaling Inhibitor",  "CDK Inhibitor; AR Signaling Inhibitor",                                                 "Ribociclib + Enzalutamide",
  "Chemotherapy",                   "5-Fluorouracil (5FU)",                                                      "5-Fluorouracil (5FU)",
  "Chemotherapy", "Adriamycin (doxorubicin hydrochloride)",                                    "Adriamycin (doxorubicin hydrochloride)",
  "Chemotherapy",               "Adrucil (5-fluorouracil)",                                                  "Adrucil (5-fluorouracil)",
  "Chemotherapy",                            "Anastrozole",                                                               "Anastrozole",
  "Chemotherapy",                            "Anastrozole",                                                                  "Arimidex",
  "Chemotherapy",                  "Avastin (bevacizumab)",                                                     "Avastin (bevacizumab)",
  "Chemotherapy",                               "Axitinib",                                                                  "Axitinib",
  "Chemotherapy",                            "Bevacizumab",                                                               "Bevacizumab",
  "Chemotherapy",                             "Bexarotene",                                                                "Bexarotene",
  "Chemotherapy",                            "Bropirimine",                                                               "Bropirimine",
  "Chemotherapy",                            "Cabazitaxel",                                                               "Cabazitaxel",
  "Chemotherapy",                            "Cabazitaxel",                                                                   "Jevtana",
  "Chemotherapy",                           "Cabozantinib",                                                              "Cabozantinib",
  "Chemotherapy",                   "Cabozantinib/Placebo",                                                      "Cabozantinib/Placebo",
  "Chemotherapy",                           "Capecitabine",                                                              "Capecitabine",
  "Chemotherapy",                           "Capecitabine",                                                     "Xeloda (capecitabine)",
  "Chemotherapy",                            "Carboplatin",                                                               "Carboplatin",
  "Chemotherapy",                            "Carboplatin",                                                  "Paraplatin (carboplatin)",
  "Chemotherapy",                             "Carmustine",                                                                "Carmustine",
  "Chemotherapy",                                  "CBDCA",                                                                     "CBDCA",
  "Chemotherapy",                           "Chemotherapy",                                                              "chemotherapy",
  "Chemotherapy",                           "Chemotherapy",                                                                    "R-CHOP",
  "Chemotherapy",                      "cis-Retinoic acid",                                                         "cis-Retinoic acid",
  "Chemotherapy",                              "Cisplatin",                                                                 "Cisplatin",
  "Chemotherapy",                              "Cisplatin",                                                      "Platinol (cisplatin)",
  "Chemotherapy",                                 "CPT-11",                                                                    "CPT-11",
  "Chemotherapy",                             "Crizotinib",                                                                "Crizotinib",
  "Chemotherapy",                       "Cyclophosphamide",                                                          "Cyclophosphamide",
  "Chemotherapy",                       "Cyclophosphamide",                                                "Cytoxan (cyclophosphamide)",
  "Chemotherapy",                       "Cyclophosphamide",                                               "Endoxana (cyclophosphamide)",
  "Chemotherapy",                       "Cyclophosphamide",                                                 "Neosar (cyclophosphamide)",
  "Chemotherapy",                              "Dasatinib",                                                                 "Dasatinib",
  "Chemotherapy",                      "Dasatinib/Placebo",                                                         "Dasatinib/Placebo",
  "Chemotherapy",                             "Dinaciclib",                                                                "Dinaciclib",
  "Chemotherapy",                              "Docetaxel",                                                                 "Docetaxel",
  "Chemotherapy",                              "Docetaxel",                                                      "Taxotere (docetaxel)",
  "Chemotherapy",              "Doxorubicin hydrochloride",                                                 "Doxorubicin hydrochloride",
  "Chemotherapy",                             "Epirubicin",                                                                "Epirubicin",
  "Chemotherapy",              "Eribulin mesylate (E7389)",                                                 "Eribulin mesylate (E7389)",
  "Chemotherapy",                              "Erlotinib",                                                                 "Erlotinib",
  "Chemotherapy",                 "Estramustine phosphate",                                                                     "Emcyt",
  "Chemotherapy",                 "Estramustine phosphate",                                         "Estracyt (estramustine phosphate)",
  "Chemotherapy",                 "Estramustine phosphate",                                                    "Estramustine phosphate",
  "Chemotherapy",                              "Etoposide",                                                                 "Etoposide",
  "Chemotherapy",                    "Everolimus (RAD001)",                                                                  "Afinitor",
  "Chemotherapy",                    "Everolimus (RAD001)",                                                       "Everolimus (RAD001)",
  "Chemotherapy",                    "Everolimus (RAD001)",                                                                  "Zortress",
  "Chemotherapy",                       "Fluoropyrimidine",                                                          "Fluoropyrimidine",
  "Chemotherapy",                           "Fluorouracil",                                                              "Fluorouracil",
  "Chemotherapy",                   "Folex (methotrexate)",                                                      "Folex (methotrexate)",
  "Chemotherapy",                            "Gemcitabine",                                                               "Gemcitabine",
  "Chemotherapy",                   "Hydrea (hydroxyurea)",                                                      "Hydrea (hydroxyurea)",
  "Chemotherapy",                            "Hydroxyurea",                                                               "Hydroxyurea",
  "Chemotherapy",                             "Idelalisib",                                                                "Idelalisib",
  "Chemotherapy",                             "Irinotecan",                                                                "Irinotecan",
  "Chemotherapy",                              "Lapatinib",                                                                 "Lapatinib",
  "Chemotherapy",                             "Leucovorin",                                                                "Leucovorin",
  "Chemotherapy",                         "Men's Taxotere",                                                            "Men's Taxotere",
  "Chemotherapy",                           "Methotrexate",                                                              "Methotrexate",
  "Chemotherapy",                              "Mitomycin",                                                                 "Mitomycin",
  "Chemotherapy",                      "Mitomycin C (MMC)",                                                         "Mitomycin C (MMC)",
  "Chemotherapy",                           "Mitoxantrone",                                                              "Mitoxantrone",
  "Chemotherapy",                           "Mitoxantrone",                                                 "Novantrone (mitoxantrone)",
  "Chemotherapy",         "Oncovin (vincristine sulphate)",                                            "Oncovin (vincristine sulphate)",
  "Chemotherapy",                            "Oxaliplatin",                                                               "Oxaliplatin",
  "Chemotherapy",                             "Paclitaxel",                                                                "Paclitaxel",
  "Chemotherapy",                             "Paclitaxel",                                                        "Taxol (paclitaxel)",
  "Chemotherapy",                              "Pazopanib",                                                                 "Pazopanib",
  "Chemotherapy",                             "Pemetrexed",                                                                "Pemetrexed",
  "Chemotherapy",                            "Pentostatin",                                                               "Pentostatin",
  "Chemotherapy",                           "Procarbazine",                                                              "Procarbazine",
  "Chemotherapy",                              "Sunitinib",                                                                 "Sunitinib",
  "Chemotherapy",                                "Suramin",                                                                   "Suramin",
  "Chemotherapy",                                 "Sutent",                                                                    "Sutent",
  "Chemotherapy",                              "Tamoxifen",                                                                 "Tamoxifen",
  "Chemotherapy",                           "Temozolomide",                                                                    "Temcad",
  "Chemotherapy",                           "Temozolomide",                                                                   "Temodal",
  "Chemotherapy",                           "Temozolomide",                                                                   "Temodar",
  "Chemotherapy",                           "Temozolomide",                                                              "Temozolomide",
  "Chemotherapy",                              "Tesetaxel",                                                                 "Tesetaxel",
  "Chemotherapy",                         "Thiotepa (THP)",                                                            "Thiotepa (THP)",
  "Chemotherapy",                       "Thymidine Kinase",                                                          "Thymidine Kinase",
  "Chemotherapy",                             "Trametinib",                                                                "Trametinib",
  "Chemotherapy",                             "Vandetanib",                                                                "Vandetanib",
  "Chemotherapy",                              "VEGF Trap",                                                                 "VEGF Trap",
  "Chemotherapy",          "Velban (vinblastine sulphate)",                                             "Velban (vinblastine sulphate)",
  "Chemotherapy",           "Velbe (vinblastine sulphate)",                                              "Velbe (vinblastine sulphate)",
  "Chemotherapy",                    "Vepesid (etoposide)",                                                       "Vepesid (etoposide)",
  "Chemotherapy",                  "Vinblastine (sulfate)",                                                     "Vinblastine (sulfate)",
  "Chemotherapy",                  "Vincristine (sulfate)",                                                     "Vincristine (sulfate)",
  "Chemotherapy",                      "VP-16 (etoposide)",                                                         "VP-16 (etoposide)",
  "Chemotherapy; ADT",                      "Chemotherapy; ADT",                                                           "Docetaxel + ADT",
  "Chemotherapy; Immunotherapy",            "Chemotherapy; Immunotherapy",                                        "Trial: Cabozantinib + Atezolizumab",
  "COX-2 Inhibitor",                              "Celecoxib",                                                                 "celecoxib",
  "Endothelin Receptor Antagonist",                    "Zibotentan (ZD4054)",                                                       "Zibotentan (ZD4054)",
  "Enhancer",                             "Cobicistat",                                                                "Cobicistat",
  "Experimental",                                 "CC-115",                             "cc115 for Enzalutamide + cc115 Clinical Trial",
  "Experimental",                           "Experimental",                                                           "CORCEPT anti-GR",
  "EZH2 Inhibitor",                               "CPI-1205",                                                                  "CPI-1205",
  "Gene Therapy",       "Suicide genes (diphtheria toxin)",                                          "Suicide genes (diphtheria toxin)",
  "GR Antagonist",              "Exicorilant (CORT 125281)",                                                                "CORT125281",
  "GR Antagonist",              "Exicorilant (CORT 125281)",                                                 "Exicorilant (CORT 125281)",
  "HSP90 Inhibitor",                    "Onalespib (AT13387)",                                                       "Onalespib (AT13387)",
  "Immunotherapy",                            "AB122 (PD1)",                                                               "AB122 (PD1)",
  "Immunotherapy",                 "AB928 (Adenosine 2ARi)",                                                    "AB928 (Adenosine 2ARi)",
  "Immunotherapy",                             "Adalimumab",                                                                "Adalimumab",
  "Immunotherapy",                                  "AdC68",                                                                     "AdC68",
  "Immunotherapy",                     "Adenovirus vectors",                                                        "Adenovirus vectors",
  "Immunotherapy",                            "Aldesleukin",                                                               "Aldesleukin",
  "Immunotherapy",                               "Anti-PD1",                                                                  "Anti-PD1",
  "Immunotherapy",                           "Atezolizumab",                                                              "Atezolizumab",
  "Immunotherapy",                               "Avelumab",                                                                  "Avelumab",
  "Immunotherapy",                           "Azathioprine",                                                              "Azathioprine",
  "Immunotherapy",                                    "BCG",                                                                       "BCG",
  "Immunotherapy",                    "Carlumab (CNTO 888)",                                                       "Carlumab (CNTO 888)",
  "Immunotherapy",                             "Cemiplimab",                                                                "Cemiplimab",
  "Immunotherapy",                           "Certolizumab",                                                              "Certolizumab",
  "Immunotherapy",                  "Cixutumumab (IMC-A12)",                                                     "Cixutumumab (IMC-A12)",
  "Immunotherapy",                             "Durvalumab",                                                                "Durvalumab",
  "Immunotherapy",                             "Durvalumab",                                                                   "Imfinzi",
  "Immunotherapy",                             "Etanercept",                                                                "Etanercept",
  "Immunotherapy",               "Figitumumab (CP-751,871)",                                                  "Figitumumab (CP-751,871)",
  "Immunotherapy",                                 "GM-CSF",                                                                    "GM-CSF",
  "Immunotherapy",                              "Golimumab",                                                                 "Golimumab",
  "Immunotherapy",                               "GPI-0100",                                                                  "GPI-0100",
  "Immunotherapy",                             "GSK2636771",                                                                "GSK2636771",
  "Immunotherapy",                  "IFN (interferon alfa)",                                                     "IFN (interferon alfa)",
  "Immunotherapy",                      "IL2 (aldesleukin)",                                                         "IL2 (aldesleukin)",
  "Immunotherapy",                          "Immunotherapy",           "AB928 (Adenosine 2ARi) + AB122 (PD1) - phase 1 trial (Powderly)",
  "Immunotherapy",                          "Immunotherapy",                 "bispecific antibody armed activated t cell clinical trial",
  "Immunotherapy",                          "Immunotherapy",                                                          "Bivalent Vaccine",
  "Immunotherapy",                          "Immunotherapy",                                                                    "CYT107",
  "Immunotherapy",                          "Immunotherapy",                                       "Immunotherapy investigational trial",
  "Immunotherapy",                          "Immunotherapy",                                                               "PSMA-Ligand",
  "Immunotherapy",                          "Immunotherapy",                                                                   "pTVG-HP",
  "Immunotherapy",                          "Immunotherapy",                                                            "TRICOM Vaccine",
  "Immunotherapy",                          "Immunotherapy",                                                                   "Vaccine",
  "Immunotherapy",                          "Immunotherapy", "Vaccine therapy against prostatic acid phosphatase phase 1 clinical trial",
  "Immunotherapy",                          "Immunotherapy",                                                             "Vaccine Trial",
  "Immunotherapy",                              "Indoximod",                                                                 "Indoximod",
  "Immunotherapy",                             "Infliximab",                                                                "Infliximab",
  "Immunotherapy",                             "Interferon",                                                                "Interferon",
  "Immunotherapy",                        "Interferon alfa",                                                           "Interferon alfa",
  "Immunotherapy",                         "Interleukin-11",                                                            "Interleukin-11",
  "Immunotherapy",                          "Interleukin-7",                                                             "Interleukin-7",
  "Immunotherapy",             "Intron A (interferon alfa)",                                                "Intron A (interferon alfa)",
  "Immunotherapy",                   "Ipilimumab (MDX-010)",                                                      "Ipilimumab (MDX-010)",
  "Immunotherapy",                   "Ipilimumab (MDX-010)",                                                                    "Yervoy",
  "Immunotherapy",                     "Ipilimumab/Placebo",                                                        "Ipilimumab/Placebo",
  "Immunotherapy",                     "Ixazomib (MLN2238)",                                                        "Ixazomib (MLN2238)",
  "Immunotherapy",             "Ixazomib Citrate (MLN9708)",                                                "Ixazomib Citrate (MLN9708)",
  "Immunotherapy",                           "JNJ-63898081",                                                              "JNJ-63898081",
  "Immunotherapy",                "Leucomax (molgramostim)",                                                   "Leucomax (molgramostim)",
  "Immunotherapy",                         "MLN-2704 (DM1)",                                                            "MLN-2704 (DM1)",
  "Immunotherapy",                                "MLN1202",                                                                   "MLN1202",
  "Immunotherapy",                           "Molgramostim",                                                              "Molgramostim",
  "Immunotherapy",                              "Nivolumab",                                                                 "Nivolumab",
  "Immunotherapy",                             "OMP-336B11",                                                                "OMP-336B11",
  "Immunotherapy",                                   "pDNA",                                                                      "pDNA",
  "Immunotherapy",                          "Pembrolizumab",                                                                  "Keytruda",
  "Immunotherapy",                          "Pembrolizumab",                                                             "Pembrolizumab",
  "Immunotherapy",                  "Pembrolizumab/Placebo",                                                            "Pembro/Placebo",
  "Immunotherapy",                  "Pembrolizumab/Placebo",                                                  "Pembrolizumab vs Placebo",
  "Immunotherapy",                            "PF-06801591",                                                               "PF-06801591",
  "Immunotherapy",                            "PF-06855992",                                                               "PF-06855992",
  "Immunotherapy",                            "plasmid DNA",                                                               "plasmid DNA",
  "Immunotherapy",                              "Poly ICLC",                                                                 "Poly-ICLC",
  "Immunotherapy",                              "Poly ICLC",                                                                 "Poly ICLC",
  "Immunotherapy",                "Proleukin (aldesleukin)",                                                   "Proleukin (aldesleukin)",
  "Immunotherapy",                            "PROSTVAC-VF",                                                               "PROSTVAC-VF",
  "Immunotherapy",                                 "PT-112",                                                                    "PT-112",
  "Immunotherapy",                                "pTVG-AR",                                                                   "pTVG-AR",
  "Immunotherapy",                       "pTVG-HP/rhGM-CSF",                                                          "pTVG-HP/rhGM-CSF",
  "Immunotherapy",                  "Rapamycin (Sirolimus)",                                                     "Rapamycin (Sirolimus)",
  "Immunotherapy",              "Roferon (interferon alfa)",                                                 "Roferon (interferon alfa)",
  "Immunotherapy",                           "Sargramostim",                                                    "Leukine (sargramostim)",
  "Immunotherapy",                           "Sargramostim",                                                              "Sargramostim",
  "Immunotherapy",                           "Sipuleucel-T",                                                                  "provenge",
  "Immunotherapy",                           "Sipuleucel-T",                                                                  "Provenge",
  "Immunotherapy",                           "Sipuleucel-T",                                                              "Sipuleucel-T",
  "Immunotherapy",                           "Sipuleucel-T",                                                   "Sipuleucel-t (provenge)",
  "Immunotherapy",                 "Spartalizumab (PDR001)",                                                                    "PDR001",
  "Immunotherapy",                 "Spartalizumab (PDR001)",                                                    "Spartalizumab (PDR001)",
  "Immunotherapy",                           "Tremelimumab",                                                              "Tremelimumab",
  "Immunotherapy",                               "Urelumab",                                                                  "Urelumab",
  "Immunotherapy",                             "Utomilumab",                                                                "Utomilumab",
  "Immunotherapy",                 "Xentuzumab (BI 836845)",                                                    "Xentuzumab (BI 836845)",
  "Immunotherapy/Placebo",                      "DCVAC/PCa/Placebo",                                                          "DCVAC or Placebo",
  "Immunotherapy/Placebo",                      "Indoximod/Placebo",                                                         "Indoximod/Placebo",
  "Immunotherapy/Placebo",                  "Pembrolizumab/Placebo",                                                     "Pembrolizumab/Placebo",
  "Matrix Metalloproteinase Inhibitor",                             "Marimastat",                                                                "Marimastat",
  "MNK1/2 Inhibitor",                                 "eFT508",                                                                    "eFT508",
  "mTOR kinase/DNA-PK Inhibitor",                                 "CC-115",                                                                    "CC-115",
  "Multi-kinase Inhibitor",                                 "ESK981",                                                                    "ESK981",
  "Nutraceutical",                              "Mistletoe",                                                                 "Mistletoe",
  "Nutraceutical",                          "Muscadine MPX",                                                             "Muscadine MPX",
  "Nutraceutical",                               "PCUR-101",                                                                  "PCUR-101",
  "Nutraceutical",                           "Saw Palmetto",                                                              "Saw Palmetto",
  "Nutraceutical/Placebo",                  "Muscadine MPX/Placebo",                                                     "Muscadine MPX/Placebo",
  "Nutraceuticals",                      "Vitamin C/Placebo",                                                     "ascorbic Acid/placebo",
  "Oligonucleotide",                    "Apatorsen (OGX-427)",                                                       "Apatorsen (OGX-427)",
  "Oligonucleotide",                              "Custirsen",                                                                 "Custirsen",
  "Oligonucleotide",                               "GDC-0068",                                                                  "GDC-0068",
  "Other",                                  "Other",                                                             "Allopurinolum",
  "Other",                                  "Other",                                                                "Amlodipino",
  "Other",                                  "Other",                                                     "Avodart (dutasteride)",
  "Other",                                  "Other",                                                           "Biresp spiromax",
  "Other",                                  "Other",                                                       "Calcimagon d3 forte",
  "Other",                                  "Other",                                                            "clinical trial",
  "Other",                                  "Other",                                                               "Dutasteride",
  "Other",                                  "Other",                                                                 "Ezetimibe",
  "Other",                                  "Other",                                                               "Finasteride",
  "Other",                                  "Other",                                                         "Hidroclorotiazida",
  "Other",                                  "Other",                                                                     "Ideos",
  "Other",                                  "Other",                                                                  "Optovite",
  "Other",                                  "Other",                                                             "Pantoprazolum",
  "Other",                                  "Other",                                                             "Pegfilgrastim",
  "Other",                                  "Other",                                                               "Perindopril",
  "Other",                                  "Other",                                               "phase 1 clinical trial drug",
  "Other",                                  "Other",                                                                    "Probic",
  "Other",                                  "Other",                                                                   "Proscar",
  "Other",                                  "Other",                                                     "Proscar (finasteride)",
  "Other",                                  "Other",                                                               "Tamsulosine",
  "Other",                                  "Other",           "testosterone for bipolar androgen therapy + nivo clinical trial",
  "Other",                  "Sodium Phenylbutyrate",                                                     "Sodium Phenylbutyrate",
  "PARP",                                "BMN-673",                                                                   "BMN-673",
  "PARP",                              "Niraparib",                                                                 "Niraparib",
  "PARP",                               "Olaparib",                                                                  "Lynparza",
  "PARP",                               "Olaparib",                                                                  "Olaparib",
  "PARP",                              "Rucaparib",                                                                   "Rubraca",
  "PARP",                              "Rucaparib",                                                                 "Rucaparib",
  "PARP",                            "Talazoparib",                                                               "Talazoparib",
  "PARP",                    "Veliparib (ABT-888)",                                                       "Veliparib (ABT-888)",
  "PARP/Placebo",                      "Niraparib/Placebo",                                                         "Niraparib/Placebo",
  "PARP/Placebo",                       "Olaparib/Placebo",                                                          "Olaparib/Placebo",
  "PARP/Placebo",                    "Talazoparib/Placebo",                                        "TALAPRO-2 (Talazoparib or Placebo)",
  "PARP/Placebo",                    "Talazoparib/Placebo",                                                    "Talazoparib or placebo",
  "PARP/Placebo",                    "Talazoparib/Placebo",                                                       "Talazoparib/Placebo",
  "PARP/Placebo",                    "Talazoparib/Placebo",                                                       "talozaparib/placebo",
  "PI3K Inhibitor",                                "AZD8186",                                                                   "AZD8186",
  "Pim Inhibitor",                                "AZD1208",                                                                   "AZD1208",
  "PLK1 Inhibitor",                  "Onvansertib (PCM-075)",                                                     "Onvansertib (PCM-075)",
  "PLK1 Inhibitor",                  "Onvansertib (PCM-075)",                                                                   "PCM-075",
  "Progesterone",                    "Medroxyprogesterone",                                "Depo-Provera (medroxyprogesterone acetate)",
  "Progesterone",                    "Medroxyprogesterone",                                    "Farlutal (medroxyprogesterone acetate)",
  "Progesterone",                    "Medroxyprogesterone",                                               "Medroxyprogesterone acetate",
  "Progesterone",                    "Medroxyprogesterone",                                     "Provera (medroxyprogesterone acetate)",
  "Progesterone",                      "Megestrol acetate",                                                "Megace (megestrol acetate)",
  "Progesterone",                      "Megestrol acetate",                                                         "Megestrol acetate",
  "Quinoline-3-carboxamide Analog",                            "Tasquinimod",                                                               "Tasquinimod",
  "Quinoline-3-carboxamide Analog",                    "Tasquinimod/Placebo",                                                       "Tasquinimod/Placebo",
  "Radiopharmaceuticals",                          "131I-MIP-1095",                                                             "131I-MIP-1095",
  "Radiopharmaceuticals",                             "177Lu-J591",                                                                "177Lu-J591",
  "Radiopharmaceuticals",                             "225Ac-J591",                                                                "225Ac-J591",
  "Radiopharmaceuticals",                             "225Ac-J591",                                                             "Actinium-J591",
  "Radiopharmaceuticals",                           "Actinium-225",                                                              "Actinium-225",
  "Radiopharmaceuticals",                           "Actinium-225",                                                     "Actinium-225-PSMA-617",
  "Radiopharmaceuticals",                                 "EC1169",                                                                    "EC1169",
  "Radiopharmaceuticals",                                  "I-131",                                                                     "I-131",
  "Radiopharmaceuticals",                                 "Iodine",                                                                    "Iodine",
  "Radiopharmaceuticals",                           "Lutetium-177",                                                              "Lutetium-177",
  "Radiopharmaceuticals",                   "Radiopharmaceuticals",                                                              "Radiotherapy",
  "Radiopharmaceuticals",                             "Radium-223",                                                                "Radium-223",
  "Radiopharmaceuticals",                             "Radium-223",                                                                    "Xofigo",
  "Radiopharmaceuticals",                             "Radium-223",                                                       "Xofigo (Radium-223)",
  "Radiopharmaceuticals",                               "Samarium",                                                      "Quadramet (samarium)",
  "Radiopharmaceuticals",                               "Samarium",                                                                  "Samarium",
  "Radiopharmaceuticals",                              "Strontium",                                                                 "Metastron",
  "Radiopharmaceuticals",                              "Strontium",                                                                 "Strontium",
  "Radiopharmaceuticals",       "Vipivotide tetraxetan (PSMA-617)",                                          "Vipivotide tetraxetan (PSMA-617)",
  "SHP2 Inhibitor",                               "RLY-1971",                                                               "ID-RLY-1971",
  "SHP2 Inhibitor",                               "RLY-1971",                                                                  "RLY-1971",
  "SK2 Selective Inhibitor",                               "Opaganib",                                                                  "Opaganib",
  "SK2 Selective Inhibitor",                               "Opaganib",                                                   "Opaganib clinical trial",
  "Src Inhibitor",                  "Saracatinib (AZD0530)",                                                     "Saracatinib (AZD0530)",
  "Steroid",                          "Dexamethasone",                                                  "Decadron (dexamethasone)",
  "Steroid",                          "Dexamethasone",                                                             "Dexamethasone",
  "Steroid",                                "GTx-758",                                                                   "GTx-758",
  "Steroid",                           "Mifepristone",                                                              "Mifepristone",
  "Steroid",                "Polyestradiol phosphate",                                      "Estradurin (polyestradiol phosphate)",
  "Steroid",                "Polyestradiol phosphate",                                                   "Polyestradiol phosphate",
  "Steroid",                           "Prednisolone",                                                  "Prednisol (prednisolone)",
  "Steroid",                           "Prednisolone",                                                              "Prednisolone",
  "Steroid",                             "Prednisone",                                                                "Prednisone",
  "Steroid",                           "Testosterone",                                                              "Testosterone",
  "TGF-ßRI kinase inhibitor",               "Galunisertib (LY2157299)",                                                              "Galunisertib",
  "TGF-ßRI kinase inhibitor",               "Galunisertib (LY2157299)",                                                  "LY2157299 (Galunisertib)",
  "TGF-ßRI kinase Inhibitor",               "Galunisertib (LY2157299)",                                                  "Galunisertib (LY2157299)",
  "Tyrosine Kinase Inhibitor",                               "SU011248",                                                                  "SU011248",
  "Wee1 inhibitor",                  "Adavosertib (AZD1775)",                                                                   "AZD1775",
  "Wee1 Inhibitor",                  "Adavosertib (AZD1775)",                                                     "Adavosertib (AZD1775)",
  "XPO1 Inhibitor",                    "Selinexor (KPT-330)",                                                       "Selinexor (KPT-330)"
) %>%
  dplyr::mutate(
    treatment_lower = tolower(treatment),
    is_taxel     =  stringr::str_detect(treatment_recode, stringr::regex("taxel", ignore_case = TRUE)),
    is_nha       =  stringr::str_detect(treatment_recode, stringr::regex("abiraterone|enzalutamide|darolutamide|apalutamide", ignore_case = TRUE))
  ) %>%
  labelled::set_variable_labels(
    treatment = "Treatment as entered",
    treatment_lower = "Treatment as entered lower case",
    treatment_category = "Assigned treatment category",
    treatment_recode = "Assigned treatment standardized coding",
    is_taxel = "Treatment is one of  Cabazitaxel, Docetaxel, Paclitaxel, Tesetaxel",
    is_nha = "Treatment is a novel hormonal agent (one of Abiraterone, Enzalutamide, Darolutamide, Apalutamide)"
  ) %>%
  dplyr::arrange(treatment_category, treatment) %>%
  dplyr::distinct()





usethis::use_data(treatment_map, overwrite = TRUE)
